// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhahyhSLX5FDfQYFv7U199B_f87nvSJjE',
    appId: '1:603275202418:web:71cddf772b10a0a8cb57eb',
    messagingSenderId: '603275202418',
    projectId: 'whiteapp-71b9e',
    authDomain: 'whiteapp-71b9e.firebaseapp.com',
    storageBucket: 'whiteapp-71b9e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9El9kribTnXcgX0q5NrfM93PkxpSDvoo',
    appId: '1:603275202418:android:ddd66ff061af5740cb57eb',
    messagingSenderId: '603275202418',
    projectId: 'whiteapp-71b9e',
    storageBucket: 'whiteapp-71b9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcgR2RBbMkaYiCwR4y3VKNjxk1RhPXkgI',
    appId: '1:603275202418:ios:ecfd39624ab6e65bcb57eb',
    messagingSenderId: '603275202418',
    projectId: 'whiteapp-71b9e',
    storageBucket: 'whiteapp-71b9e.firebasestorage.app',
    androidClientId: '603275202418-gomij01f0eejonj87qm66e5lf28v6smh.apps.googleusercontent.com',
    iosClientId: '603275202418-pi9n6pi64u05n9v4r8p4229qtul0kv9r.apps.googleusercontent.com',
    iosBundleId: 'com.example.whiteapp',
  );
}
